### ISSUE TITLE
data issue

### ISSUE THREAD

**Issue by wzjiang** [huanghoujing/EANet#1]
Thanks for your great work. I find a little problem that when I unzip duke-20190104T081615Z-001.zip there is bounding_box_train_market1501_style.tar.gz in the duke fold

**Comment by huanghoujing** [comment]
The original DukeMTMC-reID images should be downloaded from [this repository](https://github.com/layumi/DukeMTMC-reID_evaluation). `bounding_box_train_market1501_style.tar.gz` is the Duke training images transferred to Market1501 style, used in experiment `PAP_ST_PS_SPGAN`.

**Comment by wzjiang** [comment]
thanks for your reply
