### ISSUE TITLE
Error in evaluation

### ISSUE THREAD

**Issue by Anguliachao** [huanghoujing/EANet#10]
Hi @huanghoujing  , thanks for the nice repo. I tried to test the model , I can run the GlobalPool experiment successfully. However I encouter the following errors when running PAP series evaluation. 
the error msg as follows:

`  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/EANet/package/optim/eanet_trainer.py", line 133, in <module>
    trainer.test()
  File "/workspace/EANet/package/optim/reid_trainer.py", line 170, in test
    score_dict = eval_dataloader(model_for_eval, loader_dict['query'], loader_dict['gallery'], deepcopy(cfg.eval))
  File "/workspace/EANet/package/eval/eval_dataloader.py", line 18, in eval_dataloader
    q_feat_dict = extract_dataloader_feat(model, q_loader, cfg)
  File "/workspace/EANet/package/eval/extract_feat.py", line 32, in extract_dataloader_feat
    for batch in tqdm(loader, desc='Extract Feature', miniters=20, ncols=120, unit=' batches'):
  File "/opt/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: function takes exactly 5 arguments (1 given)
`
I strictly follow your instruction, but this error still occurs, would you mind helping me out?

**Comment by nayanleo** [comment]
simply go to package/config/default.py file, and make num_workers = 0
and then run again.

**Comment by Anguliachao** [comment]
> simply go to package/config/default.py file, and make num_workers = 0
> and then run again.

Thanks a lot.

**Comment by Anguliachao** [comment]
FYI, I'm using python 3.5 pytorch 1.0 version. In the meantime you might encouter the following error when try to load models
`
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal
not in range(128)
`
For this is the format decoding issues between python2 and python3, you can simply added 

`d = pickle.load(f, encoding='latin1') 
`
then can run all the PAP series evaluation experiments.
since it's already solved I will close this issue.

**Comment by nayanleo** [comment]
Hello, @Anguliachao , after solving both the errors, at the time of the training i am getting keyerror , from file, /EANet-master/package/data/dataset.py", line 78, in get_pap_mask
    kpt = self.im_path_to_kpt[key]['kpt']
KeyError: 'Market-1501-v15.09.15/query/1481_c3s3_061328_02.jpg'

had you face such type of error.
and if yes then what is the work around for.

**Comment by huanghoujing** [comment]
@nayanleo There seems some problem with your Market1501 dataset. The correct dataset has image `Market-1501-v15.09.15/query/1481_c3s3_061328_00.jpg` but not `Market-1501-v15.09.15/query/1481_c3s3_061328_02.jpg`.

**Comment by nayanleo** [comment]
@Anguliachao thanks a lot
