### ISSUE TITLE
How to generate keypoint and segmentation label for new dataset?

### ISSUE THREAD

**Issue by mittlin** [huanghoujing/EANet#11]

**Comment by huanghoujing** [comment]
There should be keypoints for new dataset. You have to train a keypoint estimation model on COCO and then use it to infer your dataset. We currently do not make our keypoint model public, and [this one](https://github.com/Microsoft/human-pose-estimation.pytorch) can be an alternative.

**Comment by mittlin** [comment]
thanks for your help !!

**Comment by mittlin** [comment]
sorry！ one more question:  there should be another ps_label file ( like DukeMTMC-reID_ps_label.tar.gz) ? how to generate?

**Comment by huanghoujing** [comment]
We are arranging our part segmentation code and will make it public soon. Attention is welcome!

**Comment by huanghoujing** [comment]
@mittlin We have released [the code for part segmentation](https://github.com/huanghoujing/PyTorch-Encoding), including training, inference and visualization.

**Comment by mittlin** [comment]
thanks! I will check it out
