### ISSUE TITLE
Result of MSMT17

### ISSUE THREAD

**Issue by lzgahbb** [huanghoujing/EANet#14]
Hi, 
Nice work! I have try experiment on MSMT17(data and experiment config is same to your paper), but I can't get results (PAP-6P, Rank-1:75.5%) as your paper shows. So, is there some different configs from other dataset ?

**Comment by huanghoujing** [comment]
Hi, thanks for your attention to this work.
- `PAP-6P, Rank-1:75.5%` is the result you get?
- There is no difference from other datasets.

**Comment by wzjiang** [comment]
could you share your config？I  have try experiment on MSMT17 and get rank-1：78.3（based on pap-6p）
