### ISSUE TITLE
implement of triplet loss

### ISSUE THREAD

**Issue by hh23333** [huanghoujing/EANet#2]
Hi,
NIce work! There have already been mang implements of tripletloss in your program, while you didn't put the results in your paper and README document. I'm concerned about how the tripletloss perform based on your algorithms. Thanks!

**Comment by huanghoujing** [comment]
I didn't implement triplet loss for experiments of the paper... But I guess this part of code, i.e. PK sampling and triplet loss calculation, is useful, so I include it in the repository as well.

**Comment by hh23333** [comment]
OK, Thank you for your reply.
