### ISSUE TITLE
About extracting features. What value should the cos distance  be set ?

### ISSUE THREAD

**Issue by shoutOutYangJie** [huanghoujing/EANet#24]
I I notice there is no any   quantitative  value of cosine distance. For example, I want to know whether two pedestrians are one person or not, and then I should calculate the cosine distence bewteen the two feature corresponding to two pedestrians respectively. But I don't know what value is suitable. So can you give me some advices. thank you!

**Comment by huanghoujing** [comment]
Hi, thanks for your attention. Person re-identification only considers ranking (or retrieval) during testing. So, it does not involve recognition. If you want to perform recognition, you have to tune the threshold by yourself. Maybe the statistical value that separates positive pairs from negative pairs in training set could be an option.

**Comment by shoutOutYangJie** [comment]
yes, I exactly did it by your way two month ago. Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Houjing Huang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 上午9:02
收件人:&nbsp;"huanghoujing/EANet"<EANet@noreply.github.com&gt;;
抄送:&nbsp;"312358434"<312358434@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghoujing/EANet] About extracting features. What value should the cos distance  be set ? (#24)




Hi, thanks for your attention. Person re-identification only considers ranking (or retrieval) during testing. So, it does not involve recognition. If you want to perform recognition, you have to tune the threshold by yourself. Maybe the statistical value that separates positive pairs from negative pairs in training set could be an option.
