### ISSUE TITLE
关于compute_dist_with_visibility函数中的余弦距离计算问题

### ISSUE THREAD

**Issue by TongYoungG** [huanghoujing/EANet#36]
作者，你好。
我看到在计算余弦距离时，compute_dist_with_visibility函数最后出现了这样一行代码：
`if dist_type == 'cosine':
    dist += 1
`
这个计算不是已经在compute_dist函数中计算过了吗，为什么这里还要再加一次？

**Comment by huanghoujing** [comment]
你好，这里`dist += 1`是为了防止距离的数值为负数，对于排序没有影响，是为了防止后续的DBSCAN聚类算法报错。
