### ISSUE TITLE
Could you share the MSMT_V1 dataset with me?

### ISSUE THREAD

**Issue by lzgahbb** [huanghoujing/EANet#7]
Because only MSMT17_V2 can be downloaded at present. It is not consistent with what you used in this paper. I will be very grateful for your sharing

**Comment by huanghoujing** [comment]
Hi, you can now see the file `MSMT17_V1.tar.gz` in the Google Drive or Baidu Cloud link in README.

**Comment by lzgahbb** [comment]
Thank you very very much!

**Comment by gyh420** [comment]
> Because only MSMT17_V2 can be downloaded at present. It is not consistent with what you used in this paper. I will be very grateful for your sharing
hi, where l can find MSMT17_v2?
