### ISSUE TITLE
how to use such repository in practicals.

### ISSUE THREAD

**Issue by nayanleo** [huanghoujing/EANet#9]
i have done all the steps described in readme.md file, also getting the score of testing as expected.
but my query is that, i want to search and re-idntify one single person realtime, can it is possible to use the above model. 
if it is possible, then anyone can explain me how we can make it sucessful for 1 person only.

notice that, we have few images of intrested person, and test it with 1 or max 2 images of intersted person.
when i am giving small amount of images in query and bounding_box_test folder, i am getting error such as ,
Extract Feature: 100%|##############################################################| 1/1 [00:01<00:00,  1.28s/ batches]
=> Eval Statistics:
	dic.keys(): dict_keys(['q_feat', 'q_label', 'q_cam', 'g_feat', 'g_label', 'g_cam'])
	dic['q_feat'].shape: (25, 512)
	dic['q_label'].shape: (25,)
	dic['q_cam'].shape: (25,)
	dic['g_feat'].shape: (5, 512)
	dic['g_label'].shape: (5,)
	dic['g_cam'].shape: (5,)

  File "/home/vikram/OBJECT DETECTION & TRACKING/EANet-master/package/eval/metric.py", line 101, in cmc
    raise RuntimeError("No valid query")
RuntimeError: No valid query

thank you in advanced.

**Comment by huanghoujing** [comment]
Hi, thanks for your attention to this project. I think you are in need of a use example to extract feature for single images. I will provide such example recently.

**Comment by nayanleo** [comment]
Hi, thanks for reply. I have done the example case but the model i used is not recognize and reid the same person. also i found one issue that, In market1501-> bounding_box_test & query folders are exists, but having the same image number for different person, it gives the output match[ True ] on concole.
provided, i ran the command : 
$ { project_dir } CUDA_VISIBLE_DEVICES=0 python -m package.optim.eanet_trainer --exp_dir exp/eanet/GlobalPool/market1501 --cfg_file package/config/default.py --ow_file paper_configs/GlobalPool.txt --ow_str "cfg.dataset.train.name = 'market1501'; cfg.only_test = True"

**Comment by nayanleo** [comment]
![screenshot from 2019-01-21 15-08-39](https://user-images.githubusercontent.com/42641434/51465711-7d85e800-1d8e-11e9-8b0e-7468e1ebd2fa.png)

see the image names starting from 1482, both in query and test folder, output is match [ True ], M->M 100%. 
but the use case is both images are of different persons.  And if I change the image names then the output " No Valid Query ". I am getting confused, what actually happens inside the model.

can you please explain me why this happens? 

is model uses the image names as the identitiies?

Is the same model is used for person recognition? (As i am gone through you research paper in detail it should recognise and  then re-id the person. )

thank you...

**Comment by huanghoujing** [comment]
The evaluation code is only used for calculating scores. For only extracting feature and showing the ranking results, I am writing an example script : )

**Comment by nayanleo** [comment]
@huanghoujing Thank you,  I am waiting for your example, However I have very basic query whether I can use this package for my own images for Re-ID score (By training on my own images and by placing my own images in test and query folder ).

**Comment by huanghoujing** [comment]
@nayanleo Hi, our inference interface is now available. You can infer image, image list, or data loader and obtain your feature.
<https://github.com/huanghoujing/EANet#traintestinference-example>
<https://github.com/huanghoujing/EANet#inference>

Since you have id annotation, you can create a new class as one of Market1501, etc. In that class, you can define your query/gallery image paths and define the id format, etc. Then, you can specify `cfg.dataset.test.names = ['YOUR-DATASET-NAME']` and `cfg.only_test = True` to test ReID scores on your data. You can use GlobalPool or PCB. If you want PAP based models, you have to provide keypoint in your dataset as well.

**Comment by nayanleo** [comment]
@huanghoujing Thank you, my previous query is solved by your guidance. But one case is how to define keypoints in own dataset and for PAP which dataset can be used to train it from the scratch. Please guide.

**Comment by huanghoujing** [comment]
@nayanleo You may use [this trained and public keypoint model](https://github.com/Microsoft/human-pose-estimation.pytorch) with state-of-the-art performance on COCO dataset.

**Comment by nayanleo** [comment]
@huanghoujing , thank you so much for the reponse. I worked on it. But again i have new query, can we train PAP_S_PS model for the given Market1501 dataset or other dataset is required for the segmentation module.
